export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const GET_SELECTED_CHAT = "GET_SELECTED_CHAT";
export const GET_ALL_CHATS = "GET_ALL_CHATS";
export const FETCH_AGAIN = "FETCH_AGAIN";